### PR TITLE
[WIP] feat: Add source maps

### PR DESCRIPTION
**Pull request by Marwes**
Resurrected another old branch which adds source maps. Currently this always creates the map which may not be desirable but it should be very low overhead and optional creation may be added later. Going to experiment with this a bit in the language server so I may need to tweak the interface of this before we can merge this.

### CODE REVIEW

**Comment by Marwes** [comment]
Oops, apparently this defaulted to a PR to the source_map branch.

**Comment by brendanzab** [comment]
If you edit the title of a PR, you can re-target the branch. Just for future reference!

**Comment by Marwes** [comment]
Oh, hadn't notice that, thanks (I'd say its not an especially intuitive way of doing it though).

**Comment by brendanzab** [comment]
Yep - it's quite odd! I only know because I stumbled upon it one day...

**Pull request closed without merging**
