### PR TITLE
fix: Fix issue #255

### LINKED ISSUE #255: Issues with REPL on osx nightly
When I run commands in the REPL, nothing is output and when I quit, it panics. 

This is on
`nightly-x86_64-apple-darwin - rustc 1.17.0-nightly (ba7cf7cc5 2017-02-11)`

After `cargo build --release` and running the binary directly:
```
$ ./target/release/gluon -i
gluon (:h for help, :q to quit)
> io.print "test"
> 1 + 2
> :q
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:868
```

When using `cargo run -- -i`
```
$ cargo run -- -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/gluon -i`
gluon (:h for help, :q to quit)
> io.print "Hello world!"
> io.println "Hello world!"
> 1 + 3
> (+) 1 2
> let x = 1 + 2 in x
> if True then 1 else 0
> :q
thread '<unnamed>' panicked at 'Attempted to pop Frame { offset: 0, instruction_index: 0, state: Unknown, excess: false } but io.catch was expected', vm/src/thread.rs:1092
stack backtrace:
   1:        0x103fd7d2c - std::sys::imp::backtrace::tracing::imp::write::h61cce32efcf6a3d0
   2:        0x103fd9afe - std::panicking::default_hook::{{closure}}::hdac93beb64eaf365
   3:        0x103fd97a0 - std::panicking::default_hook::h4a7f61136a9004ca
   4:        0x103fd9fb7 - std::panicking::rust_panic_with_hook::hdf5cd951b8d6fa36
   5:        0x103fd9e14 - std::panicking::begin_panic::h1204ab053b688140
   6:        0x103fd9d82 - std::panicking::begin_panic_fmt::h7d4fffc79f986d3b
   7:        0x10390513a - gluon_vm::thread::OwnedContext::execute_function::h8024527494b9639e
   8:        0x1039033f2 - gluon_vm::thread::OwnedContext::execute::h098316227de893b2
   9:        0x1038ff9e7 - <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_function::h311c14088dbcc79f
  10:        0x103728a0f - gluon::io::catch_io::h99943ac36cd3be3d
  11:        0x103904813 - gluon_vm::thread::OwnedContext::execute_function::h8024527494b9639e
  12:        0x1039033f2 - gluon_vm::thread::OwnedContext::execute::h098316227de893b2
  13:        0x1038ff9e7 - <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_function::h311c14088dbcc79f
  14:        0x103728a0f - gluon::io::catch_io::h99943ac36cd3be3d
  15:        0x103904813 - gluon_vm::thread::OwnedContext::execute_function::h8024527494b9639e
  16:        0x1039033f2 - gluon_vm::thread::OwnedContext::execute::h098316227de893b2
  17:        0x1038ff9e7 - <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_function::h311c14088dbcc79f
  18:        0x103728a0f - gluon::io::catch_io::h99943ac36cd3be3d
  19:        0x103904813 - gluon_vm::thread::OwnedContext::execute_function::h8024527494b9639e
  20:        0x1039033f2 - gluon_vm::thread::OwnedContext::execute::h098316227de893b2
  21:        0x1038ff9e7 - <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_function::h311c14088dbcc79f
  22:        0x103728a0f - gluon::io::catch_io::h99943ac36cd3be3d
  23:        0x103904813 - gluon_vm::thread::OwnedContext::execute_function::h8024527494b9639e
  24:        0x1039033f2 - gluon_vm::thread::OwnedContext::execute::h098316227de893b2
  25:        0x1038ff9e7 - <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_function::h311c14088dbcc79f
  26:        0x103728a0f - gluon::io::catch_io::h99943ac36cd3be3d
  27:        0x103904813 - gluon_vm::thread::OwnedContext::execute_function::h8024527494b9639e
  28:        0x1039033f2 - gluon_vm::thread::OwnedContext::execute::h098316227de893b2
  29:        0x1038ff9e7 - <gluon_vm::thread::Thread as gluon_vm::thread::ThreadInternal>::call_function::h311c14088dbcc79f
  30:        0x103582c45 - <gluon_vm::api::Function<T, fn(A) .> R>>::call_first::h51f7c7c7e226c6ae
  31:        0x10358336b - <gluon_vm::api::Function<T, fn(A) .> R>>::call::heaf3af95cc79ad67
  32:        0x1035acc58 - gluon::repl::run::he016209b5877782c
  33:        0x1035ad804 - gluon::main::{{closure}}::hbfd15dd23e00c515
  34:        0x1035a093c - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hf06a845c7578ceb9
  35:        0x10353f93c - std::panicking::try::do_call::h23f669d4993aad05
  36:        0x103fdadea - __rust_maybe_catch_panic
  37:        0x10353f7fd - std::panicking::try::h41cc25cc5c3b35f2
  38:        0x10353ebfb - std::panic::catch_unwind::haba485d157f445f2
  39:        0x10353f553 - std::thread::Builder::spawn::{{closure}}::hc8945de66c008215
  40:        0x10355e95b - <F as alloc::boxed::FnBox<A>>::call_box::h8f834685b1986eeb
  41:        0x103fd9274 - std::sys::imp::thread::Thread::new::thread_start::h6bde712098e3c94f
  42:     0x7fffb824daaa - _pthread_body
  43:     0x7fffb824d9f6 - _pthread_start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:868
stack backtrace:
   1:        0x103fd7d2c - std::sys::imp::backtrace::tracing::imp::write::h61cce32efcf6a3d0
   2:        0x103fd9afe - std::panicking::default_hook::{{closure}}::hdac93beb64eaf365
   3:        0x103fd97a0 - std::panicking::default_hook::h4a7f61136a9004ca
   4:        0x103fd9fb7 - std::panicking::rust_panic_with_hook::hdf5cd951b8d6fa36
   5:        0x103fd9e14 - std::panicking::begin_panic::h1204ab053b688140
   6:        0x103fd9d82 - std::panicking::begin_panic_fmt::h7d4fffc79f986d3b
   7:        0x103fd9ce7 - rust_begin_unwind
   8:        0x104002db0 - core::panicking::panic_fmt::he6eb92dab4407c61
   9:        0x103557dc9 - core::result::unwrap_failed::hce695648c2a404cf
  10:        0x103546246 - <core::result::Result<T, E>>::unwrap::h7e18bfaf0cffd75e
  11:        0x1035ad5b3 - gluon::main::h02544df4b0f43752
  12:        0x103fdadea - __rust_maybe_catch_panic
  13:        0x103fda386 - std::rt::lang_start::h5196b70c908371ed
  14:        0x1035ae449 - main
```

### PR DESCRIPTION
**Pull request by Marwes**
I think this should fix the missing output on osx, I changed `io.print` to not output a newline a while back and had forgotten to change the call in the repl which prints the result.

Also fixes a panic when exiting the repl, see 6afc82c8166f93e3222a2d93591bf58850a512bc for the fix and cause.

Fixes #255

### CODE REVIEW

**Comment by salpalvv** [comment]
Merged the PR and tested: 

```
$ cargo run -- -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/gluon -i`
gluon (:h for help, :q to quit)
> 1 + 2
3 : Int
> io.println "test"
GcPtr(PartialApplicationData { function: Extern(GcPtr(println 0x10077a0a0)), args: ["test"] }) : IO ()
>
```

**Comment by Marwes** [comment]
Looks like its working though I guess I should make `run_expr` execute io actions as well since that seems to have regressed. Testing on the repl could use some improvement but it seems hard at the moment https://github.com/gluon-lang/gluon/issues/51

**Comment by zipper97412** [comment]
Hi newbie here, IO doesn't seems to execute:
```
user@debian-vm-p19:~/Téléchargements/gluon/gluon$ cargo run -- -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/gluon -i`
gluon (:h for help, :q to quit)
> io.println "yolooooo"
GcPtr(PartialApplicationData { function: Extern(GcPtr(println 0x7fec35627910)), args: ["yolooooo"] }) : IO ()
> 
```
any idea on how to print my "yoloooooo"?
is that the normal behavior of the REPL?

**Comment by Marwes** [comment]
@zipper97412 No that is a bug, seems I failed to verify that the println worked. Fixed by #266. Once that is merged you can do `cargo install gluon --git https://github.com/gluon-lang/gluon`. Will do a new release once I have ironed out nested patterns.

**Comment by zipper97412** [comment]
Noice thanks you

**Pull request merged**
