### PR TITLE
Add foldable and traversable modules

### PR DESCRIPTION
**Pull request by brendanzab**

### CODE REVIEW

**Comment by brendanzab** [comment]
Weird - getting some unrelated [HTTP test failures](https://travis-ci.org/gluon-lang/gluon/jobs/271341625#L1701-L1712):

```
     Running target/debug/deps/http-4e8d70d579969949

running 2 tests
test echo ... FAILED
test http ... FAILED

failures:

---- echo stdout ----
	thread 'echo' panicked at 'assertion failed: `(left == right)`
  left: `Ok(0)`,
 right: `Ok(200)`', tests/http.rs:69:4
```

**Comment by Marwes** [comment]
Yeah I have seen that before I think those are just spurious though

**Comment by Marwes** [comment]
I should probably go through and add some logging in case it happens again.

**Comment by brendanzab** [comment]
Still seems to be failing on those tests... ignoring them for now 😕

**Comment by Marwes** [comment]
Sigh, `ld` crashes again, thought I fixed that...

**Comment by brendanzab** [comment]
Fixed some warnings - hopefully this gets it past the compile tests

**Comment by Marwes** [comment]
Hopefully, beta timed out when compiling `gluon_parser` and the new nightly seem to take far longer than usual as well...

**Comment by Marwes** [comment]
https://travis-ci.org/gluon-lang/gluon/builds/267460349 vs https://travis-ci.org/gluon-lang/gluon/builds/271386649 :/ 18 vs 28 minutes...

**Comment by brendanzab** [comment]
I nuked the [travis build caches](https://travis-ci.org/gluon-lang/gluon/caches) when I saw the ld issue pop up - hopefully it gets faster in the future 😟

**Comment by Marwes** [comment]
I wonder. Maybe the cache in Travis fills up with stale artefacts from builds with older compilers.

**Comment by brendanzab** [comment]
Interesting definition of 'passed' https://travis-ci.org/gluon-lang/gluon/jobs/271395640#L570 🤣

**Comment by Marwes** [comment]
It might be because I restarted it, and for some reason it is not marked as canceled

**Comment by brendanzab** [comment]
🍾

**Comment by Marwes** [comment]
Nice! If I get the same problems in #324 I will see if I can get to the bottom of this/send an issue on rust-lang/rust

**Pull request merged**
