### PR TITLE
Add a few QoL functions to the standard library

### PR DESCRIPTION
**Pull request by Etherian**
Adds
- `unwrap_or` and `to_result` to `Option`
- `unwrap_ok_or`, `unwrap_err_or`, and `to_option` to `Result`
- Kleisli composition operators (`<=<` and `>=>`)

### CODE REVIEW

**Comment by Marwes** [comment]
Looks like you forgot to import `<<`

**Comment by Etherian** [comment]
Fixed.

On the subject, what do you think of adding `std.function` to the prelude? I feel like I import most of it in every script.

**Comment by Marwes** [comment]
> On the subject, what do you think of adding std.function to the prelude? I feel like I import most of it in every script.

👍 Probably just `<<` and `<|` I think those are the most common to use. Maybe also Monad, Category etc as well?

**Comment by Etherian** [comment]
> > On the subject, what do you think of adding std.function to the prelude? I feel like I import most of it in every script.
> 
> +1 Probably just `<<` and `<|`? I think those are the most common to use. Maybe also Monad, Category etc as well?

I agree on both counts.

**Pull request merged**
