### PR TITLE
[WIP] feat: Add pretty printing of expressions

### LINKED ISSUE #133: Implement pretty printing of expressions
In the same way as types are pretty printed we can use the [pretty](https://github.com/freebroccolo/pretty.rs) library to also pretty print expressions. As a start this could merely be a useful debugging tool but with some work it may also be used for automatic formatting (ala rustfmt).

The fact that the syntax is indentation aware _might_ make implementating this a bit tricky though, possibly some extensions to `pretty` will be needed.

### PR DESCRIPTION
**Pull request by Marwes**
Unsure how much I will do on this but I think I will at least fix the fact that the expression after `=` or `->` does not appear on the next line (I believe this is a limitation of pretty atm).

Partially fixes #133 

# map.glu
```f#
let prelude = import "std/prelude.glu"
and { Ordering, Ord, Option, List, Monoid, } = prelude
in
type Map k a = | Bin k a (Map k a) (Map k a) | Tip
in
let empty = Tip
in
let singleton k v = Bin k v empty empty
and make ord = let find k m = match m with
        | Bin k2 v l r -> match ord.compare k k2 with
            | LT -> find k l
            | EQ -> Some v
            | GT -> find k r
        | Tip -> None
    and insert k v m = match m with
        | Bin k2 v2 l r -> match ord.compare k k2 with
            | LT -> Bin k2 v2 insert k v l r
            | EQ -> Bin k v l r
            | GT -> Bin k2 v2 l insert k v r
        | Tip -> Bin k v empty empty
    and to_list m = let ++ = prelude.monoid_List.append
        in match m with
        | Bin key value l r -> to_list l ++ Cons { key, value, } to_list r
        | Tip -> Nil
    in let append l r = match l with
        | Bin lk lv ll lr -> match r with
            | Bin rk rv rl rr -> match ord.compare lk rk with
                | LT -> Bin lk lv ll append lr r
                | EQ -> Bin lk lv append ll rl append lr rr
                | GT -> Bin lk lv append ll r lr
            | Tip -> l
        | Tip -> match r with
            | Bin a b c d -> r
            | Tip -> empty
    in let monoid = { append, empty, }
    in { monoid, singleton, find, insert, to_list, }
in
{ Map, make,
}
```

### CODE REVIEW

**Comment by Marwes** [comment]
```f#
let prelude = import "std/prelude.glu"
and { Ordering, Ord, Option, List, Monoid } = prelude
type Map k a = | Bin k a (Map k a) (Map k a) | Tip
let empty = Tip
let singleton k v = Bin k v empty empty
and make ord =
        let find k m =
                match m with
                | Bin k2 v l r -> match ord.compare k k2 with
                    | LT -> find k l
                    | EQ -> Some v
                    | GT -> find k r
                | Tip -> None
        and insert k v m =
                match m with
                | Bin k2 v2 l r -> match ord.compare k k2 with
                    | LT -> Bin k2 v2 insert k v l r
                    | EQ -> Bin k v l r
                    | GT -> Bin k2 v2 l insert k v r
                | Tip -> Bin k v empty empty
        and to_list m =
                let (++) = prelude.monoid_List.append
                match m with
                | Bin key value l r -> to_list l ++ Cons { key, value } to_list r
                | Tip -> Nil
        let append l r =
                match l with
                | Bin lk lv ll lr -> match r with
                    | Bin rk rv rl rr -> match ord.compare lk rk with
                        | LT -> Bin lk lv ll append lr r
                        | EQ -> Bin lk lv append ll rl append lr rr
                        | GT -> Bin lk lv append ll r lr
                    | Tip -> l
                | Tip -> match r with
                    | Bin a b c d -> r
                    | Tip -> empty
        let monoid = { append, empty }
        { monoid, singleton, find, insert, to_list }
{ Map, make }
```

**Comment by Marwes** [comment]
Parentheses are still missing as those are not part of the AST atm.

**Comment by brendanzab** [comment]
I'm thinking it would be safer to use prefix notation for operators, seeing as we don't know fixities and such...

Eg.

```elm
| Bin key value l r -> (++) (to_list l) (Cons { key, value } to_list r)
```
vs
```elm
| Bin key value l r -> to_list l ++ Cons { key, value } to_list r
```

**Comment by Marwes** [comment]
Since the ast itself is printed that shouldn't be an issue as long as parentheses are preserved. May be good to have a mode which prints with precis and parentheses though for debugging precedence bugs.

**Comment by brendanzab** [comment]
Might be a case for quickcheck! :D

**Comment by Marwes** [comment]
Generating ASTs and checking that `parse(pretty_print(expr)) == expr`?

**Comment by Marwes** [comment]
Update on this PR.

Made some nice progress on and got [three of the std/* files](https://github.com/gluon-lang/gluon/pull/205/files#diff-98d787dd8ec7b43c1561e61c4910503bR58) formatted according to the pretty printer. Currently stuck trying to represent unindentation.

Consider

```f#
let map f m : (a -> b) -> State s a -> State s b =
    \state ->
        let { value, state } = m state
        { value = f value, state = state }
```

Between the outer and inner `let` there are two levels of indentation which is fine and necessary but if we instead write the lambdas arguments on the line above I currently get this pretty printing


```f#
let map f m : (a -> b) -> State s a -> State s b = \state ->
        let { value, state } = m state
        { value = f value, state = state }
```

That is, the inner `let` is still indented twice. A nicer formatting would be to "unindent" after the lambda.

```f#
let map f m : (a -> b) -> State s a -> State s b = \state ->
    let { value, state } = m state
    { value = f value, state = state }
```

**Pull request merged**
