### PR TITLE
Move abstract types out of AliasData

### PR DESCRIPTION
**Pull request by brendanzab**
This cleans up a bunch of `Option` juggling and makes things a bit easier to understand!

### CODE REVIEW

**Comment by Marwes** [comment]
The option is actually not there to indicate an unknown type but it is actually an indicator of an abstract type  (such as `Array a`). Having that hidden under `Alias` is perhaps not best so refactoring it may be a good idea. The notion of an abstract type should remain though as it is used for all native types.

**Comment by brendanzab** [comment]
Ohhh, ok. Sorry for misunderstanding!

**Comment by brendanzab** [comment]
What about having an `Abstract` variant under `Type`?

**Comment by brendanzab** [comment]
Or perhaps this is a job for existentials?

**Comment by Marwes** [comment]
Yeah, was thinking something like that. Should be clearer than than how it is right now.

**Comment by brendanzab** [comment]
Ok, I made a new variant, `Opaque`. It seems that `abstract` is a reserved word in Rust 😉 

I don't fully understand how to implement existentials, or whether they would be suitable for this purpose, but this works for now.

**Comment by Marwes** [comment]
`abtstract` many be reserved but `Abstract` should not be no? `opaque` is fine as well though, any reason I am missing to not go for abstract?

**Comment by brendanzab** [comment]
What would I use for the constructor?

**Comment by brendanzab** [comment]
`abs` is for 'abstraction'. 😆

**Comment by Marwes** [comment]
Ah, forgot about it being lower case there. I guess opaque is fine then, it should not confuse anyone I hope.

**Comment by brendanzab** [comment]
`abstrakt`? 😆

**Comment by Marwes** [comment]
No? :p

**Comment by Marwes** [comment]
Lets just go with opaque

**Pull request merged**
