### PR TITLE
Update URLs to point to new organization

### LINKED ISSUE #178: Update URLs to point to new organisation
#177 transferred the repositories to the gluon-lang org. We should probably now do a find and replace across the repos to update `Marwes/` to `gluon-lang/`.

### PR DESCRIPTION
**Pull request by zjhmale**
Fixes #178 

@Marwes and please don't forget to create a new gitter channel for this 😅

### CODE REVIEW

**Comment by brendanzab** [comment]
Woow, thanks! 😍

**Comment by brendanzab** [comment]
You could also do the other repos if you were feeling adventurous! But no pressure :)

**Comment by brendanzab** [comment]
Mentioned making the new channel [on gitter](https://gitter.im/Marwes/gluon?at=57f8d3e80aa72e3c5be4e738).

Looked around at your repos - tons of nice stuff! You haven't published your Idris VS Code extension though! Was looking for a nice one a couple of weeks ago! 😆

**Comment by brendanzab** [comment]
Hah, was waiting for ages for this to pass CI, but it seems we hadn't enabled it yet!

**Comment by brendanzab** [comment]
Might have to re-push to get travis to pick it up - we have it enabled now.

**Comment by zjhmale** [comment]
@Marwes i will! and i'm really interested in the [vscode-extension](https://github.com/gluon-lang/gluon_language-server) which you reimplemented the language server protocol use Rust, awesome!
>You could also do the other repos if you were feeling adventurous! But no pressure :)

**Comment by zjhmale** [comment]
done!
>Might have to re-push to get travis to pick it up - we have it enabled now.

**Comment by Marwes** [comment]
@zhjmale Thanks. Let me know if you have any questions. It was quite simple to setup though I did have some issues with debugging it early on when I did not yet send the correct responses. Having proper types for all the responses now has made that a non issue now at least!

**Pull request merged**
